#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

"""
Structural drift-guards for the skill/ channel.

The other four delivery channels (CLI, Python API, MCP server, AgentCore
agent) fail loudly at import or registration time when a tool name is
renamed or a subcommand is removed, because the code itself references
those names. The skill files are just prose -- SKILL.md can go on referring
to a tool that no longer exists, and nobody notices until a customer's
agent calls a tool name that returns an error.

This test catches that drift. It does not test whether a model at runtime
actually follows the guardrails in guardrails.md; that would need an eval
harness with real model invocations. It only checks structural claims:

  1. Every SKILL.md has valid YAML frontmatter with name and description.
  2. Every MCP tool name mentioned in the MCP-backed track's SKILL.md
     exists in the actual MCP server's registered tool set.
  3. Every CLI subcommand mentioned in the standalone CLI track's SKILL.md
     exists in the actual CLI's argument parser.
  4. Every companion file referenced from any SKILL.md exists on disk.
  5. No hardcoded pillar or check counts appear in any skill file
     (numbers there go stale -- both skill tracks tell the agent to
     discover scope live instead).

No AWS credentials required. No model calls. Runs in under a second.

Usage:
  python tests/test_skill_integrity.py
"""

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from bedrock_readiness.modules import PILLAR_MODULES


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILL_DIR = os.path.join(REPO_ROOT, "skill")

TRACKS = {
    "mcp-backed": os.path.join(SKILL_DIR, "mcp-backed", "SKILL.md"),
    "standalone-cli": os.path.join(SKILL_DIR, "standalone-cli", "SKILL.md"),
}


# --- Frontmatter -------------------------------------------------------------


def _parse_frontmatter(text: str) -> dict:
    """Minimal YAML frontmatter parser for a SKILL.md file.

    Deliberately does NOT depend on PyYAML: this test must run with only the
    package's own dependencies. Frontmatter shape we expect:

        ---
        name: some-name
        description: >
          Multi-line
          description.
        ---
    """
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}
    body = text[4:end]
    fields = {}
    current_key = None
    current_val_lines = []
    for line in body.split("\n"):
        m = re.match(r"^([a-z_][a-z_0-9]*):\s*(.*)$", line)
        if m and not line.startswith(" "):
            if current_key is not None:
                fields[current_key] = " ".join(
                    l.strip() for l in current_val_lines if l.strip()
                ).strip()
            current_key = m.group(1)
            rest = m.group(2).strip()
            if rest and rest != ">":
                current_val_lines = [rest]
            else:
                current_val_lines = []
        elif current_key is not None:
            current_val_lines.append(line)
    if current_key is not None:
        fields[current_key] = " ".join(
            l.strip() for l in current_val_lines if l.strip()
        ).strip()
    return fields


def _check_frontmatter():
    failures = []
    for track, path in TRACKS.items():
        if not os.path.exists(path):
            failures.append(f"{track}: SKILL.md not found at {path}")
            continue
        with open(path) as f:
            text = f.read()
        fm = _parse_frontmatter(text)
        if not fm:
            failures.append(f"{track}: missing or malformed YAML frontmatter")
            continue
        for required in ("name", "description"):
            if required not in fm or not fm[required]:
                failures.append(f"{track}: frontmatter missing required field '{required}'")
        # Basic sanity: name should be a slug-like identifier, not free prose.
        name = fm.get("name", "")
        if name and not re.match(r"^[a-z][a-z0-9-]*$", name):
            failures.append(
                f"{track}: frontmatter 'name' should be a slug (lowercase, "
                f"hyphens, digits); got {name!r}"
            )
    return failures


# --- MCP tool names ----------------------------------------------------------


def _mcp_registered_tools() -> set:
    """Every tool the MCP server actually registers.

    Derived from two places:
      - `check_<pillar_id>` for each pillar in PILLAR_MODULES (generated by
        _make_pillar_tool in mcp_server.py).
      - Every function decorated with @mcp.tool() in mcp_server.py source.

    Parsing the source avoids requiring the `mcp` package as a test dependency.
    """
    tools = {f"check_{pid}" for pid in PILLAR_MODULES}
    mcp_source_path = os.path.join(
        REPO_ROOT, "bedrock_readiness", "delivery", "mcp_server.py"
    )
    with open(mcp_source_path) as f:
        lines = f.readlines()
    # Walk lines: after seeing "@mcp.tool()", find the next "def <name>(".
    saw_decorator = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("@mcp.tool("):
            saw_decorator = True
            continue
        if saw_decorator:
            m = re.match(r"def\s+([a-zA-Z_][a-zA-Z_0-9]*)\s*\(", stripped)
            if m:
                tools.add(m.group(1))
                saw_decorator = False
    return tools


# Tool names in the MCP SKILL.md are surrounded by backticks. We deliberately
# match backticked identifiers rather than every backticked token, because
# many other things (arg names, boolean values) are also in backticks. Real
# MCP tool names are snake_case identifiers we can enumerate.
def _mentioned_mcp_tools(text: str) -> set:
    candidates = set(re.findall(r"`([a-z_][a-z_0-9]*)`", text))
    # Only keep candidates that plausibly look like our tool names:
    # they must start with `check_`, `assess_`, `review_`, `list_`, or
    # `describe_`. Everything else is likely an argument, boolean, or config
    # key. This is a heuristic; the goal is to catch drift on names we
    # actually publish as tools, not to guess at every backticked token.
    keep_prefixes = ("check_", "assess_", "review_", "list_", "describe_")
    return {c for c in candidates if c.startswith(keep_prefixes)}


def _check_mcp_tool_names():
    path = TRACKS["mcp-backed"]
    if not os.path.exists(path):
        return [f"mcp-backed SKILL.md not found at {path}"]
    with open(path) as f:
        text = f.read()
    mentioned = _mentioned_mcp_tools(text)
    registered = _mcp_registered_tools()
    missing = mentioned - registered
    failures = []
    for name in sorted(missing):
        failures.append(
            f"mcp-backed SKILL.md mentions MCP tool `{name}` but no such "
            f"tool is registered by mcp_server.py "
            f"(registered: {sorted(registered)})"
        )
    return failures


# --- CLI subcommands ---------------------------------------------------------


def _cli_registered_subcommands() -> set:
    """Every subcommand the CLI's argparse registers.

    Import the CLI module and introspect. Falls back to source parsing if
    import fails for any reason -- both approaches must agree, so the
    fallback is fine as a safety net.
    """
    try:
        from bedrock_readiness import cli  # noqa: F401
        # Rebuild the parser as cli.main() does. We can't call main() (it
        # calls sys.exit), so we re-declare the subcommand names here.
        # This is a smaller surface than parsing argparse internals.
        pass
    except Exception:
        pass

    # Parse cli.py source for `sub.add_parser("<name>"...)` lines. This is
    # the authoritative surface -- the same lines that define the CLI.
    cli_source_path = os.path.join(REPO_ROOT, "bedrock_readiness", "cli.py")
    with open(cli_source_path) as f:
        src = f.read()
    return set(re.findall(r'sub\.add_parser\(\s*"([a-z-]+)"', src))


def _mentioned_cli_subcommands(text: str) -> set:
    # Match "bedrock-readiness <subcommand>" -- either in code blocks or
    # inline. The subcommand is the first token after the CLI name.
    return set(re.findall(r"bedrock-readiness\s+([a-z][a-z-]*)", text))


def _check_cli_subcommands():
    path = TRACKS["standalone-cli"]
    if not os.path.exists(path):
        return [f"standalone-cli SKILL.md not found at {path}"]
    with open(path) as f:
        text = f.read()
    mentioned = _mentioned_cli_subcommands(text)
    registered = _cli_registered_subcommands()
    # Some CLI-name-adjacent tokens aren't real subcommands (e.g.
    # "bedrock-readiness-mcp" broken across whitespace could match). Filter
    # to plausible-command-word tokens only, but any mentioned token that
    # doesn't look like it could be an arg-flag start is worth checking.
    missing = mentioned - registered
    failures = []
    for name in sorted(missing):
        failures.append(
            f"standalone-cli SKILL.md mentions CLI subcommand "
            f"`bedrock-readiness {name}` but no such subcommand is "
            f"registered by cli.py "
            f"(registered: {sorted(registered)})"
        )
    return failures


# --- File references ---------------------------------------------------------


def _mentioned_files(text: str, base_dir: str) -> set:
    """Every relative file path referenced from a SKILL.md.

    Matches Markdown link targets and bare `skill/xxx.md` references in
    backticks, since both are how a SKILL.md points at a companion file.
    """
    paths = set()
    # Bare backticked paths like `skill/guardrails.md`
    for m in re.finditer(r"`(skill/[^`]+\.md)`", text):
        paths.add(m.group(1))
    # Markdown links [label](path.md)
    for m in re.finditer(r"\]\(([^)]+\.md)\)", text):
        p = m.group(1)
        if not p.startswith("http"):
            paths.add(p)
    return paths


def _check_file_references():
    failures = []
    for track, path in TRACKS.items():
        if not os.path.exists(path):
            continue
        with open(path) as f:
            text = f.read()
        base_dir = os.path.dirname(path)
        for rel_path in _mentioned_files(text, base_dir):
            # Two resolution strategies -- both are legitimate ways to refer
            # to a shared file from a SKILL.md:
            #   a) `skill/foo.md` (repo-root-anchored -- how the docs speak
            #      about files to a human reader)
            #   b) `../foo.md` (relative to the SKILL.md's own dir)
            candidates = [
                os.path.join(REPO_ROOT, rel_path),
                os.path.join(base_dir, rel_path),
            ]
            if not any(os.path.exists(c) for c in candidates):
                failures.append(
                    f"{track}: SKILL.md references {rel_path!r} but no file "
                    f"exists at any of: {candidates}"
                )
    return failures


# --- No hardcoded counts -----------------------------------------------------


HARDCODED_COUNT_PATTERNS = [
    # "8 pillars", "eight pillars"
    (r"\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s+pillars?\b", "pillar count"),
    # "59 checks", "fifty-nine checks"
    (r"\b(\d+)\s+checks?\b", "check count"),
    # "13 tools", "N tools"
    (r"\b(\d+)\s+tools?\b", "tool count"),
]


def _check_no_hardcoded_counts():
    failures = []
    for track, path in TRACKS.items():
        if not os.path.exists(path):
            continue
        with open(path) as f:
            text = f.read()
        for pattern, label in HARDCODED_COUNT_PATTERNS:
            for m in re.finditer(pattern, text, re.IGNORECASE):
                # Filter false positives -- allow phrases like
                # "every finding" or "a few minutes" that the regex won't
                # match anyway. The regex above only matches counts followed
                # by pillar/check/tool.
                failures.append(
                    f"{track}: SKILL.md contains hardcoded {label} "
                    f"({m.group(0)!r}). Both tracks must tell the agent to "
                    f"discover scope live (call describe_scope for MCP, "
                    f"run `bedrock-readiness checks` for CLI). Numbers "
                    f"here go stale."
                )
    # Also check guardrails.md since it's shared and might drift the same way.
    guardrails = os.path.join(SKILL_DIR, "guardrails.md")
    if os.path.exists(guardrails):
        with open(guardrails) as f:
            text = f.read()
        for pattern, label in HARDCODED_COUNT_PATTERNS:
            for m in re.finditer(pattern, text, re.IGNORECASE):
                failures.append(
                    f"guardrails.md contains hardcoded {label} "
                    f"({m.group(0)!r}); this file must be scope-free."
                )
    return failures


# --- Runner ------------------------------------------------------------------


def main():
    print("Skill integrity checks")
    print("=" * 60)

    all_failures = []
    for name, fn in [
        ("Frontmatter validity", _check_frontmatter),
        ("MCP tool names exist", _check_mcp_tool_names),
        ("CLI subcommands exist", _check_cli_subcommands),
        ("Referenced files exist", _check_file_references),
        ("No hardcoded counts", _check_no_hardcoded_counts),
    ]:
        failures = fn()
        status = "PASS" if not failures else "FAIL"
        print(f"[{status}] {name}")
        for f in failures:
            print(f"       - {f}")
        all_failures.extend(failures)

    print("=" * 60)
    if all_failures:
        print(f"FAILED: {len(all_failures)} issue(s) found.")
        sys.exit(1)
    print("All skill integrity checks passed.")
    sys.exit(0)


if __name__ == "__main__":
    main()
